name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        sdl_version: ["2.0.14", "2.0.14", "2.0.14"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev

      - name: Install dependencies
        if: matrix.os == 'windows-latest'
        run: |
          choco install sdl2 sdl2-ttf sdl2-mixer --version=$env:sdl_version

      - name: Configure and build
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          cmake -B build -S .
          cmake --build build --config Release

      - name: Configure and build
        if: matrix.os == 'windows-latest'
        run: |
          cmake -B build -S . -G "Visual Studio 16 2019" -A x64
          cmake --build build --config Release

      - name: Package
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          mkdir release
          mv build/ArkaPong release/
          tar -czvf ArkaPong_${{ matrix.os }}_${{ github.run_number }}.tar.gz release/*

      - name: Package
        if: matrix.os == 'windows-latest'
        run: |
          mkdir release
          mv build/Release/ArkaPong.exe release/
          7z a ArkaPong_${{ matrix.os }}_${{ github.run_number }}.zip release/*

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ArkaPong_${{ matrix.os }}_${{ github.run_number }}
          path: ArkaPong_${{ matrix.os }}_${{ github.run_number }}.*
